"""Data models and validation schemas package."""

from src.models.entities import (
    Base,
    Candidate,
    CandidateExperience,
    CandidateSkill,
    IngestionBatch,
    IngestionError,
    JobDescription,
    JobSkill,
    MatchingEvaluation,
    OperationalMetric,
    Skill,
    create_db_engine,
    get_session_factory,
    init_db,
)
from src.models.schemas import (
    CandidateProfileDTO,
    CandidateSkillDTO,
    IngestionBatchSummaryDTO,
    JobPostingDTO,
    JobSkillRequirementDTO,
    MatchingEvaluationDTO,
    RawCandidateSchema,
    RawExperienceInput,
    RawJobDescriptionSchema,
    RawJobSkillInput,
    RawOperationalMetricSchema,
    RawSkillInput,
)

__all__ = [
    "Base",
    "Candidate",
    "CandidateExperience",
    "CandidateSkill",
    "IngestionBatch",
    "IngestionError",
    "JobDescription",
    "JobSkill",
    "MatchingEvaluation",
    "OperationalMetric",
    "Skill",
    "create_db_engine",
    "get_session_factory",
    "init_db",
    "CandidateProfileDTO",
    "CandidateSkillDTO",
    "IngestionBatchSummaryDTO",
    "JobPostingDTO",
    "JobSkillRequirementDTO",
    "MatchingEvaluationDTO",
    "RawCandidateSchema",
    "RawExperienceInput",
    "RawJobDescriptionSchema",
    "RawJobSkillInput",
    "RawOperationalMetricSchema",
    "RawSkillInput",
]
